// Toán khó - Challenge tư duy: Tìm số thiếu, dãy số, bài toán lời văn nâng cao
export const mathQuestionsHard = [
  // === TÌM SỐ CÒN THIẾU ===
  { question_text: "? + 7 = 15", option_a: "8", option_b: "7", option_c: "9", option_d: "6", correct_answer: "a" },
  { question_text: "12 + ? = 20", option_a: "7", option_b: "8", option_c: "9", option_d: "6", correct_answer: "b" },
  { question_text: "? - 5 = 13", option_a: "17", option_b: "19", option_c: "18", option_d: "16", correct_answer: "c" },
  { question_text: "25 - ? = 17", option_a: "7", option_b: "9", option_c: "6", option_d: "8", correct_answer: "d" },
  { question_text: "? + 15 = 32", option_a: "17", option_b: "16", option_c: "18", option_d: "15", correct_answer: "a" },
  { question_text: "? - 23 = 19", option_a: "41", option_b: "42", option_c: "40", option_d: "43", correct_answer: "b" },
  { question_text: "34 + ? = 51", option_a: "16", option_b: "18", option_c: "17", option_d: "15", correct_answer: "c" },
  { question_text: "? + 28 = 65", option_a: "36", option_b: "38", option_c: "35", option_d: "37", correct_answer: "d" },
  { question_text: "72 - ? = 45", option_a: "27", option_b: "26", option_c: "28", option_d: "25", correct_answer: "a" },
  { question_text: "? x 3 = 12", option_a: "3", option_b: "4", option_c: "5", option_d: "6", correct_answer: "b" },
  { question_text: "? x 5 = 25", option_a: "4", option_b: "6", option_c: "5", option_d: "3", correct_answer: "c" },
  { question_text: "? x 4 = 20", option_a: "4", option_b: "6", option_c: "3", option_d: "5", correct_answer: "d" },
  { question_text: "? x 2 = 18", option_a: "9", option_b: "8", option_c: "10", option_d: "7", correct_answer: "a" },
  { question_text: "? : 3 = 7", option_a: "18", option_b: "21", option_c: "24", option_d: "15", correct_answer: "b" },
  { question_text: "? : 4 = 6", option_a: "20", option_b: "28", option_c: "24", option_d: "16", correct_answer: "c" },
  // === DÃY SỐ QUY LUẬT ===
  { question_text: "Tìm số tiếp theo: 2, 4, 6, 8, ?", option_a: "9", option_b: "11", option_c: "12", option_d: "10", correct_answer: "d" },
  { question_text: "Tìm số tiếp theo: 5, 10, 15, 20, ?", option_a: "25", option_b: "22", option_c: "30", option_d: "24", correct_answer: "a" },
  { question_text: "Tìm số tiếp theo: 1, 3, 5, 7, ?", option_a: "8", option_b: "9", option_c: "10", option_d: "11", correct_answer: "b" },
  { question_text: "Tìm số tiếp theo: 3, 6, 9, 12, ?", option_a: "14", option_b: "16", option_c: "15", option_d: "13", correct_answer: "c" },
  { question_text: "Tìm số tiếp theo: 10, 20, 30, 40, ?", option_a: "45", option_b: "55", option_c: "60", option_d: "50", correct_answer: "d" },
  { question_text: "Tìm số tiếp theo: 1, 2, 4, 8, ?", option_a: "16", option_b: "10", option_c: "12", option_d: "14", correct_answer: "a" },
  { question_text: "Tìm số còn thiếu: 2, 4, ?, 8, 10", option_a: "5", option_b: "6", option_c: "7", option_d: "3", correct_answer: "b" },
  { question_text: "Tìm số còn thiếu: 5, 10, ?, 20, 25", option_a: "12", option_b: "14", option_c: "15", option_d: "16", correct_answer: "c" },
  { question_text: "Tìm số tiếp theo: 4, 8, 12, 16, ?", option_a: "18", option_b: "22", option_c: "24", option_d: "20", correct_answer: "d" },
  { question_text: "Tìm số tiếp theo: 100, 90, 80, 70, ?", option_a: "60", option_b: "50", option_c: "65", option_d: "55", correct_answer: "a" },
  { question_text: "Tìm số tiếp theo: 50, 45, 40, 35, ?", option_a: "25", option_b: "30", option_c: "32", option_d: "28", correct_answer: "b" },
  { question_text: "Tìm số còn thiếu: 1, 4, 9, 16, ?", option_a: "20", option_b: "24", option_c: "25", option_d: "21", correct_answer: "c" },
  { question_text: "Tìm số tiếp theo: 2, 5, 8, 11, ?", option_a: "12", option_b: "13", option_c: "15", option_d: "14", correct_answer: "d" },
  { question_text: "Tìm số tiếp theo: 1, 1, 2, 3, 5, ?", option_a: "8", option_b: "7", option_c: "6", option_d: "9", correct_answer: "a" },
  { question_text: "Tìm số còn thiếu: 3, 6, ?, 12, 15", option_a: "8", option_b: "9", option_c: "10", option_d: "7", correct_answer: "b" },
  // === BÀI TOÁN LỜI VĂN NÂNG CAO ===
  { question_text: "An có 35 viên bi, An cho Bình 12 viên rồi mẹ cho An thêm 8 viên. An có mấy viên bi?", option_a: "30", option_b: "32", option_c: "31", option_d: "29", correct_answer: "c" },
  { question_text: "Một sợi dây dài 1m, cắt đi 35cm. Sợi dây còn lại dài mấy cm?", option_a: "55cm", option_b: "75cm", option_c: "60cm", option_d: "65cm", correct_answer: "d" },
  { question_text: "Mẹ mua 4 hộp sữa, mỗi hộp 5000đ. Mẹ phải trả bao nhiêu tiền?", option_a: "20000đ", option_b: "15000đ", option_c: "25000đ", option_d: "10000đ", correct_answer: "a" },
  { question_text: "Lớp có 36 học sinh xếp thành 4 hàng đều nhau. Mỗi hàng có mấy bạn?", option_a: "8", option_b: "9", option_c: "10", option_d: "7", correct_answer: "b" },
  { question_text: "Bình có 50 trang sách. Ngày thứ nhất đọc 15 trang, ngày thứ hai đọc 20 trang. Còn mấy trang chưa đọc?", option_a: "10", option_b: "20", option_c: "15", option_d: "25", correct_answer: "c" },
  { question_text: "Một con gà đẻ 5 quả trứng mỗi tuần. Hỏi 3 tuần đẻ được mấy quả?", option_a: "12", option_b: "8", option_c: "10", option_d: "15", correct_answer: "d" },
  { question_text: "Có 24 cái kẹo chia đều cho 3 bạn. Mỗi bạn được mấy cái kẹo?", option_a: "8", option_b: "7", option_c: "9", option_d: "6", correct_answer: "a" },
  { question_text: "Lan cao 1m 15cm, Hoa cao 1m 8cm. Lan cao hơn Hoa mấy cm?", option_a: "5cm", option_b: "7cm", option_c: "10cm", option_d: "8cm", correct_answer: "b" },
  { question_text: "Xe buýt có 45 chỗ, đã có 28 người ngồi. Còn mấy chỗ trống?", option_a: "15", option_b: "18", option_c: "17", option_d: "16", correct_answer: "c" },
  { question_text: "Mẹ có 100000đ, mua gạo 45000đ, mua rau 15000đ. Mẹ còn lại bao nhiêu?", option_a: "30000đ", option_b: "35000đ", option_c: "45000đ", option_d: "40000đ", correct_answer: "d" },

  // === TÍNH NHANH ===
  { question_text: "15 + 15 + 15 = ? (Tính nhanh)", option_a: "45", option_b: "40", option_c: "50", option_d: "35", correct_answer: "a" },
  { question_text: "99 + 1 = ?", option_a: "99", option_b: "100", option_c: "101", option_d: "98", correct_answer: "b" },
  { question_text: "50 + 50 - 20 = ?", option_a: "70", option_b: "90", option_c: "80", option_d: "60", correct_answer: "c" },
  { question_text: "25 + 25 + 25 + 25 = ?", option_a: "75", option_b: "90", option_c: "80", option_d: "100", correct_answer: "d" },
  { question_text: "10 x 5 - 20 = ?", option_a: "30", option_b: "25", option_c: "35", option_d: "40", correct_answer: "a" },
  { question_text: "3 x 4 + 2 x 5 = ?", option_a: "20", option_b: "22", option_c: "18", option_d: "24", correct_answer: "b" },
  { question_text: "100 - 35 - 25 = ?", option_a: "30", option_b: "50", option_c: "40", option_d: "45", correct_answer: "c" },
  { question_text: "5 x 5 + 5 = ?", option_a: "25", option_b: "35", option_c: "20", option_d: "30", correct_answer: "d" },
  { question_text: "2 x 2 x 2 x 2 = ?", option_a: "16", option_b: "8", option_c: "12", option_d: "14", correct_answer: "a" },
  { question_text: "45 + 55 = ?", option_a: "90", option_b: "100", option_c: "95", option_d: "105", correct_answer: "b" },

  // === LOGIC VÀ TƯ DUY ===
  { question_text: "Nếu hôm nay là thứ Ba, thì ngày mai là thứ mấy?", option_a: "Thứ Hai", option_b: "Thứ Ba", option_c: "Thứ Tư", option_d: "Thứ Năm", correct_answer: "c" },
  { question_text: "Nếu hôm nay là thứ Bảy, thì hôm qua là thứ mấy?", option_a: "Thứ Tư", option_b: "Chủ Nhật", option_c: "Thứ Bảy", option_d: "Thứ Sáu", correct_answer: "d" },
  { question_text: "An cao hơn Bình, Bình cao hơn Cường. Ai cao nhất?", option_a: "An", option_b: "Bình", option_c: "Cường", option_d: "Bình và Cường", correct_answer: "a" },
  { question_text: "Lan lớn hơn Mai 2 tuổi. Mai 7 tuổi. Lan mấy tuổi?", option_a: "5", option_b: "9", option_c: "8", option_d: "10", correct_answer: "b" },
  { question_text: "Có 3 hộp, mỗi hộp có 4 viên bi đỏ và 3 viên bi xanh. Tổng có mấy viên bi?", option_a: "18", option_b: "12", option_c: "21", option_d: "15", correct_answer: "c" },
  { question_text: "Một hình vuông có cạnh 5cm. Chu vi hình vuông là bao nhiêu?", option_a: "15cm", option_b: "10cm", option_c: "25cm", option_d: "20cm", correct_answer: "d" },
  { question_text: "Một hình chữ nhật có chiều dài 6cm, chiều rộng 4cm. Chu vi là?", option_a: "20cm", option_b: "24cm", option_c: "10cm", option_d: "18cm", correct_answer: "a" },
  { question_text: "Tổng của số lớn nhất có 1 chữ số và số nhỏ nhất có 2 chữ số là?", option_a: "18", option_b: "19", option_c: "10", option_d: "20", correct_answer: "b" },
  { question_text: "Hiệu của số lớn nhất có 2 chữ số và số nhỏ nhất có 2 chữ số là?", option_a: "88", option_b: "90", option_c: "89", option_d: "91", correct_answer: "c" },
  { question_text: "Số có 2 chữ số mà tổng 2 chữ số bằng 5, chữ số hàng chục là 2. Số đó là?", option_a: "25", option_b: "52", option_c: "32", option_d: "23", correct_answer: "d" },
  { question_text: "Tìm 2 số có tổng bằng 10 và hiệu bằng 4?", option_a: "7 và 3", option_b: "6 và 4", option_c: "8 và 2", option_d: "5 và 5", correct_answer: "a" },
  { question_text: "Mẹ hơn con 25 tuổi. Con 7 tuổi. Mẹ bao nhiêu tuổi?", option_a: "30", option_b: "32", option_c: "18", option_d: "35", correct_answer: "b" },
  { question_text: "Có bao nhiêu số có 2 chữ số mà chữ số hàng đơn vị là 5?", option_a: "8", option_b: "10", option_c: "9", option_d: "7", correct_answer: "c" },
  { question_text: "Một đoạn thẳng dài 12cm được chia thành 4 phần bằng nhau. Mỗi phần dài mấy cm?", option_a: "2cm", option_b: "4cm", option_c: "6cm", option_d: "3cm", correct_answer: "d" },
  { question_text: "5 + 5 + 5 + 5 có thể viết thành phép nhân nào?", option_a: "5 x 4", option_b: "4 x 4", option_c: "5 x 5", option_d: "4 x 5", correct_answer: "a" },

  // === THÊM BÀI TOÁN TƯ DUY ===
  { question_text: "Có 5 người bắt tay nhau, mỗi người bắt tay 1 lần. Có tất cả mấy cái bắt tay?", option_a: "8", option_b: "10", option_c: "5", option_d: "20", correct_answer: "b" },
  { question_text: "Cắt 1 sợi dây thành 5 đoạn thì cần cắt mấy lần?", option_a: "5", option_b: "3", option_c: "4", option_d: "6", correct_answer: "c" },
  { question_text: "Trồng 1 hàng cây gồm 6 cây, mỗi cây cách nhau 3m. Hàng cây dài mấy m?", option_a: "18m", option_b: "12m", option_c: "21m", option_d: "15m", correct_answer: "d" },
  { question_text: "Năm nay em 7 tuổi. 5 năm nữa em mấy tuổi?", option_a: "12", option_b: "11", option_c: "13", option_d: "10", correct_answer: "a" },
  { question_text: "Năm nay bố 35 tuổi. 3 năm trước bố mấy tuổi?", option_a: "33", option_b: "32", option_c: "38", option_d: "30", correct_answer: "b" },
  { question_text: "Một con ốc sên bò lên cột cao 10m. Mỗi ngày bò lên 3m, đêm tụt xuống 1m. Hỏi sau 4 ngày ốc sên ở độ cao mấy m?", option_a: "10m", option_b: "12m", option_c: "8m", option_d: "6m", correct_answer: "c" },
  { question_text: "Có 3 con mèo, mỗi con bắt được 2 con chuột mỗi ngày. Hỏi 2 ngày bắt được mấy con chuột?", option_a: "10", option_b: "6", option_c: "8", option_d: "12", correct_answer: "d" },
  { question_text: "Tổng 3 số liên tiếp bằng 15. Ba số đó là?", option_a: "4, 5, 6", option_b: "3, 4, 5", option_c: "5, 6, 7", option_d: "6, 7, 8", correct_answer: "a" },
  { question_text: "Một hình tam giác có 3 cạnh lần lượt là 3cm, 4cm, 5cm. Chu vi là?", option_a: "10cm", option_b: "12cm", option_c: "15cm", option_d: "9cm", correct_answer: "b" },
  { question_text: "Số lớn nhất có 2 chữ số khác nhau là?", option_a: "99", option_b: "90", option_c: "98", option_d: "89", correct_answer: "c" },
];
