// Toán dễ - Ôn lớp 1: Cộng trừ trong phạm vi 20, so sánh số, đếm
export const mathQuestionsEasy = [
  // === PHÉP CỘNG TRONG PHẠM VI 10 ===
  { question_text: "1 + 1 = ?", option_a: "2", option_b: "3", option_c: "1", option_d: "4", correct_answer: "a" },
  { question_text: "1 + 2 = ?", option_a: "4", option_b: "3", option_c: "2", option_d: "5", correct_answer: "b" },
  { question_text: "2 + 2 = ?", option_a: "3", option_b: "5", option_c: "4", option_d: "6", correct_answer: "c" },
  { question_text: "2 + 3 = ?", option_a: "4", option_b: "6", option_c: "3", option_d: "5", correct_answer: "d" },
  { question_text: "3 + 2 = ?", option_a: "5", option_b: "4", option_c: "6", option_d: "7", correct_answer: "a" },
  { question_text: "3 + 3 = ?", option_a: "5", option_b: "6", option_c: "7", option_d: "8", correct_answer: "b" },
  { question_text: "4 + 1 = ?", option_a: "4", option_b: "6", option_c: "5", option_d: "3", correct_answer: "c" },
  { question_text: "4 + 2 = ?", option_a: "5", option_b: "7", option_c: "8", option_d: "6", correct_answer: "d" },
  { question_text: "4 + 3 = ?", option_a: "7", option_b: "6", option_c: "8", option_d: "5", correct_answer: "a" },
  { question_text: "4 + 4 = ?", option_a: "7", option_b: "8", option_c: "9", option_d: "6", correct_answer: "b" },
  { question_text: "5 + 1 = ?", option_a: "7", option_b: "5", option_c: "6", option_d: "4", correct_answer: "c" },
  { question_text: "5 + 2 = ?", option_a: "6", option_b: "8", option_c: "5", option_d: "7", correct_answer: "d" },
  { question_text: "5 + 3 = ?", option_a: "8", option_b: "7", option_c: "9", option_d: "6", correct_answer: "a" },
  { question_text: "5 + 4 = ?", option_a: "8", option_b: "9", option_c: "7", option_d: "10", correct_answer: "b" },
  { question_text: "5 + 5 = ?", option_a: "9", option_b: "8", option_c: "10", option_d: "11", correct_answer: "c" },
  { question_text: "6 + 1 = ?", option_a: "8", option_b: "6", option_c: "5", option_d: "7", correct_answer: "d" },
  { question_text: "6 + 2 = ?", option_a: "8", option_b: "7", option_c: "9", option_d: "6", correct_answer: "a" },
  { question_text: "6 + 3 = ?", option_a: "8", option_b: "9", option_c: "7", option_d: "10", correct_answer: "b" },
  { question_text: "6 + 4 = ?", option_a: "9", option_b: "8", option_c: "10", option_d: "11", correct_answer: "c" },
  { question_text: "7 + 1 = ?", option_a: "9", option_b: "7", option_c: "6", option_d: "8", correct_answer: "d" },
  { question_text: "7 + 2 = ?", option_a: "9", option_b: "8", option_c: "10", option_d: "7", correct_answer: "a" },
  { question_text: "7 + 3 = ?", option_a: "9", option_b: "10", option_c: "8", option_d: "11", correct_answer: "b" },
  { question_text: "8 + 1 = ?", option_a: "7", option_b: "8", option_c: "9", option_d: "10", correct_answer: "c" },
  { question_text: "8 + 2 = ?", option_a: "9", option_b: "8", option_c: "11", option_d: "10", correct_answer: "d" },
  { question_text: "9 + 1 = ?", option_a: "10", option_b: "9", option_c: "11", option_d: "8", correct_answer: "a" },
  // === PHÉP CỘNG TRONG PHẠM VI 20 ===
  { question_text: "9 + 2 = ?", option_a: "10", option_b: "11", option_c: "12", option_d: "13", correct_answer: "b" },
  { question_text: "9 + 3 = ?", option_a: "11", option_b: "10", option_c: "12", option_d: "13", correct_answer: "c" },
  { question_text: "9 + 4 = ?", option_a: "12", option_b: "11", option_c: "14", option_d: "13", correct_answer: "d" },
  { question_text: "9 + 5 = ?", option_a: "14", option_b: "13", option_c: "12", option_d: "15", correct_answer: "a" },
  { question_text: "9 + 6 = ?", option_a: "14", option_b: "15", option_c: "16", option_d: "13", correct_answer: "b" },
  { question_text: "9 + 7 = ?", option_a: "15", option_b: "17", option_c: "16", option_d: "14", correct_answer: "c" },
  { question_text: "9 + 8 = ?", option_a: "16", option_b: "18", option_c: "15", option_d: "17", correct_answer: "d" },
  { question_text: "9 + 9 = ?", option_a: "18", option_b: "17", option_c: "19", option_d: "16", correct_answer: "a" },
  { question_text: "8 + 3 = ?", option_a: "10", option_b: "11", option_c: "12", option_d: "9", correct_answer: "b" },
  { question_text: "8 + 4 = ?", option_a: "11", option_b: "10", option_c: "12", option_d: "13", correct_answer: "c" },
  { question_text: "8 + 5 = ?", option_a: "12", option_b: "14", option_c: "11", option_d: "13", correct_answer: "d" },
  { question_text: "8 + 6 = ?", option_a: "14", option_b: "13", option_c: "12", option_d: "15", correct_answer: "a" },
  { question_text: "8 + 7 = ?", option_a: "14", option_b: "15", option_c: "16", option_d: "13", correct_answer: "b" },
  { question_text: "8 + 8 = ?", option_a: "15", option_b: "14", option_c: "16", option_d: "17", correct_answer: "c" },
  { question_text: "7 + 4 = ?", option_a: "10", option_b: "12", option_c: "9", option_d: "11", correct_answer: "d" },
  { question_text: "7 + 5 = ?", option_a: "12", option_b: "11", option_c: "13", option_d: "10", correct_answer: "a" },
  { question_text: "7 + 6 = ?", option_a: "12", option_b: "13", option_c: "14", option_d: "11", correct_answer: "b" },
  { question_text: "7 + 7 = ?", option_a: "13", option_b: "15", option_c: "14", option_d: "12", correct_answer: "c" },
  { question_text: "7 + 8 = ?", option_a: "14", option_b: "16", option_c: "13", option_d: "15", correct_answer: "d" },
  { question_text: "6 + 5 = ?", option_a: "11", option_b: "10", option_c: "12", option_d: "9", correct_answer: "a" },
  { question_text: "6 + 6 = ?", option_a: "11", option_b: "12", option_c: "13", option_d: "10", correct_answer: "b" },
  { question_text: "6 + 7 = ?", option_a: "12", option_b: "14", option_c: "13", option_d: "11", correct_answer: "c" },
  { question_text: "6 + 8 = ?", option_a: "13", option_b: "12", option_c: "15", option_d: "14", correct_answer: "d" },
  { question_text: "6 + 9 = ?", option_a: "15", option_b: "14", option_c: "16", option_d: "13", correct_answer: "a" },
  { question_text: "5 + 6 = ?", option_a: "10", option_b: "11", option_c: "12", option_d: "9", correct_answer: "b" },
  // === PHÉP TRỪ TRONG PHẠM VI 10 ===
  { question_text: "3 - 1 = ?", option_a: "1", option_b: "3", option_c: "2", option_d: "4", correct_answer: "c" },
  { question_text: "4 - 1 = ?", option_a: "2", option_b: "4", option_c: "1", option_d: "3", correct_answer: "d" },
  { question_text: "4 - 2 = ?", option_a: "2", option_b: "3", option_c: "1", option_d: "4", correct_answer: "a" },
  { question_text: "5 - 1 = ?", option_a: "3", option_b: "4", option_c: "5", option_d: "2", correct_answer: "b" },
  { question_text: "5 - 2 = ?", option_a: "2", option_b: "4", option_c: "3", option_d: "1", correct_answer: "c" },
  { question_text: "5 - 3 = ?", option_a: "3", option_b: "1", option_c: "4", option_d: "2", correct_answer: "d" },
  { question_text: "6 - 1 = ?", option_a: "5", option_b: "4", option_c: "6", option_d: "3", correct_answer: "a" },
  { question_text: "6 - 2 = ?", option_a: "3", option_b: "4", option_c: "5", option_d: "2", correct_answer: "b" },
  { question_text: "6 - 3 = ?", option_a: "4", option_b: "2", option_c: "3", option_d: "5", correct_answer: "c" },
  { question_text: "6 - 4 = ?", option_a: "3", option_b: "1", option_c: "4", option_d: "2", correct_answer: "d" },
  { question_text: "7 - 1 = ?", option_a: "6", option_b: "5", option_c: "7", option_d: "4", correct_answer: "a" },
  { question_text: "7 - 2 = ?", option_a: "4", option_b: "5", option_c: "6", option_d: "3", correct_answer: "b" },
  { question_text: "7 - 3 = ?", option_a: "3", option_b: "5", option_c: "4", option_d: "2", correct_answer: "c" },
  { question_text: "7 - 4 = ?", option_a: "4", option_b: "2", option_c: "5", option_d: "3", correct_answer: "d" },
  { question_text: "8 - 1 = ?", option_a: "7", option_b: "6", option_c: "8", option_d: "5", correct_answer: "a" },
  { question_text: "8 - 2 = ?", option_a: "5", option_b: "6", option_c: "7", option_d: "4", correct_answer: "b" },
  { question_text: "8 - 3 = ?", option_a: "4", option_b: "6", option_c: "5", option_d: "3", correct_answer: "c" },
  { question_text: "8 - 4 = ?", option_a: "5", option_b: "3", option_c: "6", option_d: "4", correct_answer: "d" },
  { question_text: "8 - 5 = ?", option_a: "3", option_b: "4", option_c: "2", option_d: "5", correct_answer: "a" },
  { question_text: "9 - 1 = ?", option_a: "7", option_b: "8", option_c: "9", option_d: "6", correct_answer: "b" },
  { question_text: "9 - 2 = ?", option_a: "6", option_b: "8", option_c: "7", option_d: "5", correct_answer: "c" },
  { question_text: "9 - 3 = ?", option_a: "5", option_b: "7", option_c: "4", option_d: "6", correct_answer: "d" },
  { question_text: "9 - 4 = ?", option_a: "5", option_b: "4", option_c: "6", option_d: "3", correct_answer: "a" },
  { question_text: "9 - 5 = ?", option_a: "3", option_b: "4", option_c: "5", option_d: "2", correct_answer: "b" },
  { question_text: "10 - 1 = ?", option_a: "8", option_b: "10", option_c: "9", option_d: "7", correct_answer: "c" },
  // === PHÉP TRỪ TRONG PHẠM VI 20 ===
  { question_text: "10 - 2 = ?", option_a: "7", option_b: "9", option_c: "6", option_d: "8", correct_answer: "d" },
  { question_text: "10 - 3 = ?", option_a: "7", option_b: "8", option_c: "6", option_d: "9", correct_answer: "a" },
  { question_text: "10 - 4 = ?", option_a: "5", option_b: "6", option_c: "7", option_d: "4", correct_answer: "b" },
  { question_text: "10 - 5 = ?", option_a: "4", option_b: "6", option_c: "5", option_d: "3", correct_answer: "c" },
  { question_text: "11 - 2 = ?", option_a: "8", option_b: "10", option_c: "7", option_d: "9", correct_answer: "d" },
  { question_text: "11 - 3 = ?", option_a: "8", option_b: "7", option_c: "9", option_d: "6", correct_answer: "a" },
  { question_text: "11 - 4 = ?", option_a: "6", option_b: "7", option_c: "8", option_d: "5", correct_answer: "b" },
  { question_text: "11 - 5 = ?", option_a: "5", option_b: "7", option_c: "6", option_d: "4", correct_answer: "c" },
  { question_text: "12 - 3 = ?", option_a: "8", option_b: "10", option_c: "7", option_d: "9", correct_answer: "d" },
  { question_text: "12 - 4 = ?", option_a: "8", option_b: "7", option_c: "9", option_d: "6", correct_answer: "a" },
  { question_text: "12 - 5 = ?", option_a: "6", option_b: "7", option_c: "8", option_d: "5", correct_answer: "b" },
  { question_text: "12 - 6 = ?", option_a: "5", option_b: "7", option_c: "6", option_d: "4", correct_answer: "c" },
  { question_text: "13 - 4 = ?", option_a: "8", option_b: "10", option_c: "7", option_d: "9", correct_answer: "d" },
  { question_text: "13 - 5 = ?", option_a: "8", option_b: "7", option_c: "9", option_d: "6", correct_answer: "a" },
  { question_text: "13 - 6 = ?", option_a: "6", option_b: "7", option_c: "8", option_d: "5", correct_answer: "b" },
  { question_text: "14 - 5 = ?", option_a: "8", option_b: "10", option_c: "9", option_d: "7", correct_answer: "c" },
  { question_text: "14 - 6 = ?", option_a: "7", option_b: "9", option_c: "6", option_d: "8", correct_answer: "d" },
  { question_text: "14 - 7 = ?", option_a: "7", option_b: "6", option_c: "8", option_d: "5", correct_answer: "a" },
  { question_text: "15 - 6 = ?", option_a: "8", option_b: "9", option_c: "7", option_d: "10", correct_answer: "b" },
  { question_text: "15 - 7 = ?", option_a: "7", option_b: "9", option_c: "8", option_d: "6", correct_answer: "c" },
  { question_text: "15 - 8 = ?", option_a: "6", option_b: "8", option_c: "5", option_d: "7", correct_answer: "d" },
  { question_text: "16 - 7 = ?", option_a: "9", option_b: "8", option_c: "10", option_d: "7", correct_answer: "a" },
  { question_text: "16 - 8 = ?", option_a: "7", option_b: "8", option_c: "9", option_d: "6", correct_answer: "b" },
  { question_text: "16 - 9 = ?", option_a: "8", option_b: "6", option_c: "7", option_d: "5", correct_answer: "c" },
  { question_text: "17 - 8 = ?", option_a: "8", option_b: "10", option_c: "7", option_d: "9", correct_answer: "d" },
  { question_text: "17 - 9 = ?", option_a: "8", option_b: "7", option_c: "9", option_d: "6", correct_answer: "a" },
  { question_text: "18 - 9 = ?", option_a: "8", option_b: "9", option_c: "10", option_d: "7", correct_answer: "b" },
  { question_text: "19 - 9 = ?", option_a: "9", option_b: "8", option_c: "10", option_d: "11", correct_answer: "c" },
  { question_text: "20 - 10 = ?", option_a: "9", option_b: "11", option_c: "8", option_d: "10", correct_answer: "d" },
  { question_text: "20 - 5 = ?", option_a: "15", option_b: "14", option_c: "16", option_d: "13", correct_answer: "a" },
  // === SO SÁNH SỐ ===
  { question_text: "Số nào lớn hơn: 5 hay 3?", option_a: "3", option_b: "5", option_c: "Bằng nhau", option_d: "Không biết", correct_answer: "b" },
  { question_text: "Số nào lớn hơn: 7 hay 9?", option_a: "7", option_b: "Bằng nhau", option_c: "9", option_d: "Không biết", correct_answer: "c" },
  { question_text: "Số nào nhỏ hơn: 4 hay 8?", option_a: "8", option_b: "Bằng nhau", option_c: "Không biết", option_d: "4", correct_answer: "d" },
  { question_text: "Số nào lớn hơn: 12 hay 15?", option_a: "15", option_b: "12", option_c: "Bằng nhau", option_d: "Không biết", correct_answer: "a" },
  { question_text: "Số nào nhỏ hơn: 11 hay 6?", option_a: "11", option_b: "6", option_c: "Bằng nhau", option_d: "Không biết", correct_answer: "b" },
  { question_text: "Số nào lớn hơn: 18 hay 13?", option_a: "13", option_b: "Bằng nhau", option_c: "18", option_d: "Không biết", correct_answer: "c" },
  { question_text: "Số nào nhỏ hơn: 20 hay 14?", option_a: "20", option_b: "Bằng nhau", option_c: "Không biết", option_d: "14", correct_answer: "d" },
  { question_text: "Điền dấu: 5 ... 8", option_a: "<", option_b: ">", option_c: "=", option_d: "Không biết", correct_answer: "a" },
  { question_text: "Điền dấu: 9 ... 6", option_a: "<", option_b: ">", option_c: "=", option_d: "Không biết", correct_answer: "b" },
  { question_text: "Điền dấu: 7 ... 7", option_a: "<", option_b: ">", option_c: "=", option_d: "Không biết", correct_answer: "c" },
  { question_text: "Điền dấu: 12 ... 15", option_a: ">", option_b: "=", option_c: "Không biết", option_d: "<", correct_answer: "d" },
  { question_text: "Điền dấu: 16 ... 10", option_a: ">", option_b: "<", option_c: "=", option_d: "Không biết", correct_answer: "a" },
  { question_text: "Điền dấu: 11 ... 11", option_a: "<", option_b: "=", option_c: ">", option_d: "Không biết", correct_answer: "b" },
  { question_text: "Số lớn nhất trong: 3, 7, 5, 2?", option_a: "3", option_b: "5", option_c: "7", option_d: "2", correct_answer: "c" },
  { question_text: "Số nhỏ nhất trong: 8, 4, 6, 9?", option_a: "8", option_b: "6", option_c: "9", option_d: "4", correct_answer: "d" },
  { question_text: "Số lớn nhất trong: 12, 18, 15, 10?", option_a: "18", option_b: "15", option_c: "12", option_d: "10", correct_answer: "a" },
  { question_text: "Số nhỏ nhất trong: 14, 11, 17, 13?", option_a: "14", option_b: "11", option_c: "17", option_d: "13", correct_answer: "b" },
  { question_text: "Sắp xếp từ bé đến lớn: 5, 2, 8, 1", option_a: "8, 5, 2, 1", option_b: "2, 1, 5, 8", option_c: "1, 2, 5, 8", option_d: "1, 5, 2, 8", correct_answer: "c" },
  { question_text: "Sắp xếp từ lớn đến bé: 3, 9, 6, 1", option_a: "1, 3, 6, 9", option_b: "3, 6, 9, 1", option_c: "6, 9, 3, 1", option_d: "9, 6, 3, 1", correct_answer: "d" },
  { question_text: "Số liền sau số 7 là?", option_a: "8", option_b: "6", option_c: "9", option_d: "7", correct_answer: "a" },
  // === SỐ LIỀN TRƯỚC, LIỀN SAU ===
  { question_text: "Số liền trước số 5 là?", option_a: "6", option_b: "4", option_c: "3", option_d: "5", correct_answer: "b" },
  { question_text: "Số liền sau số 9 là?", option_a: "8", option_b: "9", option_c: "10", option_d: "11", correct_answer: "c" },
  { question_text: "Số liền trước số 10 là?", option_a: "11", option_b: "8", option_c: "10", option_d: "9", correct_answer: "d" },
  { question_text: "Số liền sau số 14 là?", option_a: "15", option_b: "13", option_c: "16", option_d: "14", correct_answer: "a" },
  { question_text: "Số liền trước số 12 là?", option_a: "13", option_b: "11", option_c: "10", option_d: "12", correct_answer: "b" },
  { question_text: "Số liền sau số 19 là?", option_a: "18", option_b: "19", option_c: "20", option_d: "21", correct_answer: "c" },
  { question_text: "Số liền trước số 16 là?", option_a: "17", option_b: "14", option_c: "16", option_d: "15", correct_answer: "d" },
  { question_text: "Số nào đứng giữa 7 và 9?", option_a: "8", option_b: "6", option_c: "10", option_d: "7", correct_answer: "a" },
  { question_text: "Số nào đứng giữa 14 và 16?", option_a: "13", option_b: "15", option_c: "17", option_d: "14", correct_answer: "b" },
  { question_text: "Số nào đứng giữa 10 và 12?", option_a: "9", option_b: "13", option_c: "11", option_d: "10", correct_answer: "c" },

  // === ĐẾM HÌNH ===
  { question_text: "Có 3 quả táo, thêm 2 quả nữa. Có tất cả mấy quả?", option_a: "4", option_b: "6", option_c: "3", option_d: "5", correct_answer: "d" },
  { question_text: "Có 7 con chim, bay đi 3 con. Còn lại mấy con?", option_a: "4", option_b: "3", option_c: "5", option_d: "2", correct_answer: "a" },
  { question_text: "Có 5 bông hoa đỏ và 4 bông hoa vàng. Có tất cả mấy bông?", option_a: "8", option_b: "9", option_c: "10", option_d: "7", correct_answer: "b" },
  { question_text: "Có 10 viên bi, cho bạn 4 viên. Còn lại mấy viên?", option_a: "5", option_b: "7", option_c: "6", option_d: "4", correct_answer: "c" },
  { question_text: "Có 6 con mèo và 6 con chó. Có tất cả mấy con?", option_a: "10", option_b: "11", option_c: "13", option_d: "12", correct_answer: "d" },
  { question_text: "Có 8 cái kẹo, ăn 3 cái. Còn lại mấy cái?", option_a: "5", option_b: "4", option_c: "6", option_d: "3", correct_answer: "a" },
  { question_text: "Có 4 quyển vở, mua thêm 5 quyển. Có tất cả mấy quyển?", option_a: "8", option_b: "9", option_c: "10", option_d: "7", correct_answer: "b" },
  { question_text: "Có 15 học sinh, về 7 bạn. Còn lại mấy bạn?", option_a: "7", option_b: "9", option_c: "8", option_d: "6", correct_answer: "c" },
  { question_text: "Có 9 con gà và 8 con vịt. Có tất cả mấy con?", option_a: "16", option_b: "18", option_c: "15", option_d: "17", correct_answer: "d" },
  { question_text: "Có 11 cây bút, cho bạn 5 cây. Còn lại mấy cây?", option_a: "6", option_b: "5", option_c: "7", option_d: "4", correct_answer: "a" },

  // === PHÉP CỘNG CÓ 3 SỐ ===
  { question_text: "2 + 3 + 1 = ?", option_a: "5", option_b: "6", option_c: "7", option_d: "4", correct_answer: "b" },
  { question_text: "1 + 4 + 2 = ?", option_a: "6", option_b: "8", option_c: "7", option_d: "5", correct_answer: "c" },
  { question_text: "3 + 3 + 2 = ?", option_a: "7", option_b: "9", option_c: "6", option_d: "8", correct_answer: "d" },
  { question_text: "4 + 2 + 3 = ?", option_a: "9", option_b: "8", option_c: "10", option_d: "7", correct_answer: "a" },
  { question_text: "5 + 1 + 4 = ?", option_a: "9", option_b: "10", option_c: "11", option_d: "8", correct_answer: "b" },
  { question_text: "2 + 5 + 3 = ?", option_a: "9", option_b: "11", option_c: "10", option_d: "8", correct_answer: "c" },
  { question_text: "3 + 4 + 5 = ?", option_a: "11", option_b: "10", option_c: "13", option_d: "12", correct_answer: "d" },
  { question_text: "6 + 2 + 4 = ?", option_a: "12", option_b: "11", option_c: "10", option_d: "13", correct_answer: "a" },
  { question_text: "4 + 4 + 4 = ?", option_a: "11", option_b: "12", option_c: "13", option_d: "10", correct_answer: "b" },
  { question_text: "5 + 5 + 5 = ?", option_a: "14", option_b: "16", option_c: "15", option_d: "13", correct_answer: "c" },

  // === SỐ CHẴN, SỐ LẺ ===
  { question_text: "Số nào là số chẵn?", option_a: "3", option_b: "5", option_c: "7", option_d: "4", correct_answer: "d" },
  { question_text: "Số nào là số lẻ?", option_a: "7", option_b: "2", option_c: "4", option_d: "6", correct_answer: "a" },
  { question_text: "Số chẵn nhỏ nhất là?", option_a: "1", option_b: "2", option_c: "0", option_d: "4", correct_answer: "b" },
  { question_text: "Số lẻ lớn nhất trong: 3, 5, 8, 9?", option_a: "3", option_b: "5", option_c: "9", option_d: "8", correct_answer: "c" },
  { question_text: "Có bao nhiêu số chẵn từ 1 đến 10?", option_a: "4", option_b: "6", option_c: "3", option_d: "5", correct_answer: "d" },

  // === HÌNH HỌC CƠ BẢN ===
  { question_text: "Hình vuông có mấy cạnh?", option_a: "4", option_b: "3", option_c: "5", option_d: "6", correct_answer: "a" },
  { question_text: "Hình tam giác có mấy cạnh?", option_a: "4", option_b: "3", option_c: "5", option_d: "2", correct_answer: "b" },
  { question_text: "Hình tròn có mấy cạnh?", option_a: "1", option_b: "2", option_c: "0", option_d: "4", correct_answer: "c" },
  { question_text: "Hình chữ nhật có mấy góc vuông?", option_a: "2", option_b: "3", option_c: "5", option_d: "4", correct_answer: "d" },
  { question_text: "Hình nào có 3 cạnh?", option_a: "Hình tam giác", option_b: "Hình vuông", option_c: "Hình tròn", option_d: "Hình chữ nhật", correct_answer: "a" },
];
