// Toán trung bình - Lớp 2: Cộng trừ có nhớ, bảng nhân, đo lường, đọc giờ
export const mathQuestionsMedium = [
  // === CỘNG CÓ NHỚ TRONG PHẠM VI 100 ===
  { question_text: "Đặt tính:\n  25\n+ 17\n———", option_a: "42", option_b: "41", option_c: "43", option_d: "40", correct_answer: "a" },
  { question_text: "Đặt tính:\n  36\n+ 28\n———", option_a: "63", option_b: "64", option_c: "62", option_d: "65", correct_answer: "b" },
  { question_text: "Đặt tính:\n  47\n+ 35\n———", option_a: "81", option_b: "83", option_c: "82", option_d: "80", correct_answer: "c" },
  { question_text: "Đặt tính:\n  58\n+ 24\n———", option_a: "81", option_b: "83", option_c: "80", option_d: "82", correct_answer: "d" },
  { question_text: "Đặt tính:\n  19\n+ 43\n———", option_a: "62", option_b: "61", option_c: "63", option_d: "60", correct_answer: "a" },
  { question_text: "Đặt tính:\n  27\n+ 56\n———", option_a: "82", option_b: "83", option_c: "81", option_d: "84", correct_answer: "b" },
  { question_text: "Đặt tính:\n  38\n+ 45\n———", option_a: "82", option_b: "84", option_c: "83", option_d: "81", correct_answer: "c" },
  { question_text: "Đặt tính:\n  46\n+ 37\n———", option_a: "82", option_b: "84", option_c: "81", option_d: "83", correct_answer: "d" },
  { question_text: "Đặt tính:\n  55\n+ 28\n———", option_a: "83", option_b: "82", option_c: "84", option_d: "81", correct_answer: "a" },
  { question_text: "Đặt tính:\n  64\n+ 19\n———", option_a: "82", option_b: "83", option_c: "81", option_d: "84", correct_answer: "b" },
  { question_text: "Đặt tính:\n  29\n+ 34\n———", option_a: "62", option_b: "64", option_c: "63", option_d: "61", correct_answer: "c" },
  { question_text: "Đặt tính:\n  48\n+ 36\n———", option_a: "83", option_b: "82", option_c: "85", option_d: "84", correct_answer: "d" },
  { question_text: "Đặt tính:\n  57\n+ 25\n———", option_a: "82", option_b: "81", option_c: "83", option_d: "80", correct_answer: "a" },
  { question_text: "Đặt tính:\n  33\n+ 49\n———", option_a: "81", option_b: "82", option_c: "80", option_d: "83", correct_answer: "b" },
  { question_text: "Đặt tính:\n  66\n+ 18\n———", option_a: "83", option_b: "85", option_c: "84", option_d: "82", correct_answer: "c" },
  { question_text: "Đặt tính:\n  75\n+ 16\n———", option_a: "90", option_b: "92", option_c: "89", option_d: "91", correct_answer: "d" },
  { question_text: "Đặt tính:\n  44\n+ 38\n———", option_a: "82", option_b: "81", option_c: "83", option_d: "80", correct_answer: "a" },
  { question_text: "Đặt tính:\n  53\n+ 29\n———", option_a: "81", option_b: "82", option_c: "80", option_d: "83", correct_answer: "b" },
  { question_text: "Đặt tính:\n  67\n+ 15\n———", option_a: "81", option_b: "83", option_c: "82", option_d: "80", correct_answer: "c" },
  { question_text: "Đặt tính:\n  39\n+ 47\n———", option_a: "85", option_b: "87", option_c: "84", option_d: "86", correct_answer: "d" },

  // === TRỪ CÓ NHỚ TRONG PHẠM VI 100 ===
  { question_text: "Đặt tính:\n  42\n- 17\n———", option_a: "25", option_b: "24", option_c: "26", option_d: "23", correct_answer: "a" },
  { question_text: "Đặt tính:\n  53\n- 28\n———", option_a: "24", option_b: "25", option_c: "26", option_d: "23", correct_answer: "b" },
  { question_text: "Đặt tính:\n  61\n- 34\n———", option_a: "26", option_b: "28", option_c: "27", option_d: "25", correct_answer: "c" },
  { question_text: "Đặt tính:\n  74\n- 46\n———", option_a: "27", option_b: "29", option_c: "26", option_d: "28", correct_answer: "d" },
  { question_text: "Đặt tính:\n  85\n- 37\n———", option_a: "48", option_b: "47", option_c: "49", option_d: "46", correct_answer: "a" },
  { question_text: "Đặt tính:\n  92\n- 55\n———", option_a: "36", option_b: "37", option_c: "38", option_d: "35", correct_answer: "b" },
  { question_text: "Đặt tính:\n  63\n- 29\n———", option_a: "33", option_b: "35", option_c: "34", option_d: "32", correct_answer: "c" },
  { question_text: "Đặt tính:\n  71\n- 43\n———", option_a: "27", option_b: "29", option_c: "26", option_d: "28", correct_answer: "d" },
  { question_text: "Đặt tính:\n  80\n- 36\n———", option_a: "44", option_b: "43", option_c: "45", option_d: "42", correct_answer: "a" },
  { question_text: "Đặt tính:\n  56\n- 18\n———", option_a: "37", option_b: "38", option_c: "39", option_d: "36", correct_answer: "b" },
  { question_text: "Đặt tính:\n  94\n- 57\n———", option_a: "36", option_b: "38", option_c: "37", option_d: "35", correct_answer: "c" },
  { question_text: "Đặt tính:\n  82\n- 45\n———", option_a: "36", option_b: "38", option_c: "35", option_d: "37", correct_answer: "d" },
  { question_text: "Đặt tính:\n  73\n- 38\n———", option_a: "35", option_b: "34", option_c: "36", option_d: "33", correct_answer: "a" },
  { question_text: "Đặt tính:\n  60\n- 24\n———", option_a: "35", option_b: "36", option_c: "34", option_d: "37", correct_answer: "b" },
  { question_text: "Đặt tính:\n  91\n- 63\n———", option_a: "27", option_b: "29", option_c: "28", option_d: "26", correct_answer: "c" },
  // === BẢNG NHÂN 2 ===
  { question_text: "2 x 1 = ?", option_a: "1", option_b: "3", option_c: "4", option_d: "2", correct_answer: "d" },
  { question_text: "2 x 2 = ?", option_a: "4", option_b: "3", option_c: "5", option_d: "6", correct_answer: "a" },
  { question_text: "2 x 3 = ?", option_a: "4", option_b: "6", option_c: "5", option_d: "8", correct_answer: "b" },
  { question_text: "2 x 4 = ?", option_a: "6", option_b: "10", option_c: "8", option_d: "4", correct_answer: "c" },
  { question_text: "2 x 5 = ?", option_a: "8", option_b: "12", option_c: "6", option_d: "10", correct_answer: "d" },
  { question_text: "2 x 6 = ?", option_a: "12", option_b: "10", option_c: "14", option_d: "8", correct_answer: "a" },
  { question_text: "2 x 7 = ?", option_a: "12", option_b: "14", option_c: "16", option_d: "10", correct_answer: "b" },
  { question_text: "2 x 8 = ?", option_a: "14", option_b: "18", option_c: "16", option_d: "12", correct_answer: "c" },
  { question_text: "2 x 9 = ?", option_a: "16", option_b: "20", option_c: "14", option_d: "18", correct_answer: "d" },
  { question_text: "2 x 10 = ?", option_a: "20", option_b: "18", option_c: "22", option_d: "16", correct_answer: "a" },

  // === BẢNG NHÂN 3 ===
  { question_text: "3 x 1 = ?", option_a: "2", option_b: "3", option_c: "4", option_d: "6", correct_answer: "b" },
  { question_text: "3 x 2 = ?", option_a: "5", option_b: "9", option_c: "6", option_d: "3", correct_answer: "c" },
  { question_text: "3 x 3 = ?", option_a: "6", option_b: "12", option_c: "3", option_d: "9", correct_answer: "d" },
  { question_text: "3 x 4 = ?", option_a: "12", option_b: "9", option_c: "15", option_d: "6", correct_answer: "a" },
  { question_text: "3 x 5 = ?", option_a: "12", option_b: "15", option_c: "18", option_d: "9", correct_answer: "b" },
  { question_text: "3 x 6 = ?", option_a: "15", option_b: "21", option_c: "18", option_d: "12", correct_answer: "c" },
  { question_text: "3 x 7 = ?", option_a: "18", option_b: "24", option_c: "15", option_d: "21", correct_answer: "d" },
  { question_text: "3 x 8 = ?", option_a: "24", option_b: "21", option_c: "27", option_d: "18", correct_answer: "a" },
  { question_text: "3 x 9 = ?", option_a: "24", option_b: "27", option_c: "30", option_d: "21", correct_answer: "b" },
  { question_text: "3 x 10 = ?", option_a: "27", option_b: "33", option_c: "30", option_d: "24", correct_answer: "c" },

  // === BẢNG NHÂN 4 ===
  { question_text: "4 x 1 = ?", option_a: "3", option_b: "8", option_c: "2", option_d: "4", correct_answer: "d" },
  { question_text: "4 x 2 = ?", option_a: "8", option_b: "6", option_c: "10", option_d: "4", correct_answer: "a" },
  { question_text: "4 x 3 = ?", option_a: "8", option_b: "12", option_c: "16", option_d: "10", correct_answer: "b" },
  { question_text: "4 x 4 = ?", option_a: "12", option_b: "20", option_c: "16", option_d: "8", correct_answer: "c" },
  { question_text: "4 x 5 = ?", option_a: "16", option_b: "24", option_c: "12", option_d: "20", correct_answer: "d" },
  { question_text: "4 x 6 = ?", option_a: "24", option_b: "20", option_c: "28", option_d: "16", correct_answer: "a" },
  { question_text: "4 x 7 = ?", option_a: "24", option_b: "28", option_c: "32", option_d: "20", correct_answer: "b" },
  { question_text: "4 x 8 = ?", option_a: "28", option_b: "36", option_c: "32", option_d: "24", correct_answer: "c" },
  { question_text: "4 x 9 = ?", option_a: "32", option_b: "40", option_c: "28", option_d: "36", correct_answer: "d" },
  { question_text: "4 x 10 = ?", option_a: "40", option_b: "36", option_c: "44", option_d: "32", correct_answer: "a" },
  // === BẢNG NHÂN 5 ===
  { question_text: "5 x 1 = ?", option_a: "4", option_b: "5", option_c: "10", option_d: "6", correct_answer: "b" },
  { question_text: "5 x 2 = ?", option_a: "5", option_b: "15", option_c: "10", option_d: "8", correct_answer: "c" },
  { question_text: "5 x 3 = ?", option_a: "10", option_b: "20", option_c: "5", option_d: "15", correct_answer: "d" },
  { question_text: "5 x 4 = ?", option_a: "20", option_b: "15", option_c: "25", option_d: "10", correct_answer: "a" },
  { question_text: "5 x 5 = ?", option_a: "20", option_b: "25", option_c: "30", option_d: "15", correct_answer: "b" },
  { question_text: "5 x 6 = ?", option_a: "25", option_b: "35", option_c: "30", option_d: "20", correct_answer: "c" },
  { question_text: "5 x 7 = ?", option_a: "30", option_b: "40", option_c: "25", option_d: "35", correct_answer: "d" },
  { question_text: "5 x 8 = ?", option_a: "40", option_b: "35", option_c: "45", option_d: "30", correct_answer: "a" },
  { question_text: "5 x 9 = ?", option_a: "40", option_b: "45", option_c: "50", option_d: "35", correct_answer: "b" },
  { question_text: "5 x 10 = ?", option_a: "45", option_b: "55", option_c: "50", option_d: "40", correct_answer: "c" },

  // === PHÉP CHIA CHO 2, 3, 4, 5 ===
  { question_text: "6 : 2 = ?", option_a: "2", option_b: "4", option_c: "5", option_d: "3", correct_answer: "d" },
  { question_text: "8 : 2 = ?", option_a: "4", option_b: "3", option_c: "5", option_d: "6", correct_answer: "a" },
  { question_text: "10 : 2 = ?", option_a: "4", option_b: "5", option_c: "6", option_d: "3", correct_answer: "b" },
  { question_text: "12 : 2 = ?", option_a: "5", option_b: "7", option_c: "6", option_d: "4", correct_answer: "c" },
  { question_text: "14 : 2 = ?", option_a: "6", option_b: "8", option_c: "5", option_d: "7", correct_answer: "d" },
  { question_text: "9 : 3 = ?", option_a: "3", option_b: "2", option_c: "4", option_d: "6", correct_answer: "a" },
  { question_text: "12 : 3 = ?", option_a: "3", option_b: "4", option_c: "5", option_d: "6", correct_answer: "b" },
  { question_text: "15 : 3 = ?", option_a: "4", option_b: "6", option_c: "5", option_d: "3", correct_answer: "c" },
  { question_text: "18 : 3 = ?", option_a: "5", option_b: "7", option_c: "3", option_d: "6", correct_answer: "d" },
  { question_text: "21 : 3 = ?", option_a: "7", option_b: "6", option_c: "8", option_d: "9", correct_answer: "a" },
  { question_text: "12 : 4 = ?", option_a: "2", option_b: "3", option_c: "4", option_d: "6", correct_answer: "b" },
  { question_text: "16 : 4 = ?", option_a: "3", option_b: "5", option_c: "4", option_d: "6", correct_answer: "c" },
  { question_text: "20 : 4 = ?", option_a: "4", option_b: "6", option_c: "3", option_d: "5", correct_answer: "d" },
  { question_text: "24 : 4 = ?", option_a: "6", option_b: "5", option_c: "7", option_d: "8", correct_answer: "a" },
  { question_text: "15 : 5 = ?", option_a: "2", option_b: "3", option_c: "4", option_d: "5", correct_answer: "b" },
  { question_text: "20 : 5 = ?", option_a: "3", option_b: "5", option_c: "4", option_d: "6", correct_answer: "c" },
  { question_text: "25 : 5 = ?", option_a: "4", option_b: "6", option_c: "3", option_d: "5", correct_answer: "d" },
  { question_text: "30 : 5 = ?", option_a: "6", option_b: "5", option_c: "7", option_d: "4", correct_answer: "a" },
  { question_text: "35 : 5 = ?", option_a: "6", option_b: "7", option_c: "8", option_d: "5", correct_answer: "b" },
  { question_text: "40 : 5 = ?", option_a: "7", option_b: "9", option_c: "8", option_d: "6", correct_answer: "c" },
  // === ĐO LƯỜNG (cm, m, kg, lít) ===
  { question_text: "1m = ? cm", option_a: "10", option_b: "1000", option_c: "50", option_d: "100", correct_answer: "d" },
  { question_text: "50cm + 50cm = ? m", option_a: "1", option_b: "10", option_c: "100", option_d: "2", correct_answer: "a" },
  { question_text: "1m - 30cm = ? cm", option_a: "30", option_b: "70", option_c: "80", option_d: "60", correct_answer: "b" },
  { question_text: "2m = ? cm", option_a: "20", option_b: "2000", option_c: "200", option_d: "100", correct_answer: "c" },
  { question_text: "1kg = ? g", option_a: "10", option_b: "100", option_c: "10000", option_d: "1000", correct_answer: "d" },
  { question_text: "Cây bút dài khoảng bao nhiêu?", option_a: "15cm", option_b: "15m", option_c: "15km", option_d: "15mm", correct_answer: "a" },
  { question_text: "Chiều cao cửa lớp khoảng bao nhiêu?", option_a: "20cm", option_b: "2m", option_c: "20m", option_d: "200m", correct_answer: "b" },
  { question_text: "Quyển vở dày khoảng bao nhiêu?", option_a: "5m", option_b: "50cm", option_c: "5mm", option_d: "5cm", correct_answer: "c" },
  { question_text: "30cm + 20cm = ?", option_a: "40cm", option_b: "60cm", option_c: "10cm", option_d: "50cm", correct_answer: "d" },
  { question_text: "1m 20cm = ? cm", option_a: "120", option_b: "12", option_c: "1020", option_d: "102", correct_answer: "a" },

  // === ĐỌC GIỜ ĐỒNG HỒ ===
  { question_text: "Kim ngắn chỉ số 3, kim dài chỉ số 12. Mấy giờ?", option_a: "12 giờ", option_b: "3 giờ", option_c: "3 giờ 12 phút", option_d: "12 giờ 3 phút", correct_answer: "b" },
  { question_text: "Kim ngắn chỉ số 7, kim dài chỉ số 12. Mấy giờ?", option_a: "12 giờ", option_b: "12 giờ 7 phút", option_c: "7 giờ", option_d: "7 giờ 12 phút", correct_answer: "c" },
  { question_text: "Kim ngắn chỉ số 9, kim dài chỉ số 6. Mấy giờ?", option_a: "6 giờ 9 phút", option_b: "9 giờ 6 phút", option_c: "6 giờ", option_d: "9 giờ 30 phút", correct_answer: "d" },
  { question_text: "Kim ngắn chỉ giữa 2 và 3, kim dài chỉ số 6. Mấy giờ?", option_a: "2 giờ 30 phút", option_b: "3 giờ", option_c: "2 giờ 6 phút", option_d: "6 giờ 30 phút", correct_answer: "a" },
  { question_text: "8 giờ 30 phút, kim dài chỉ số mấy?", option_a: "8", option_b: "6", option_c: "12", option_d: "3", correct_answer: "b" },
  { question_text: "Buổi sáng em đi học lúc mấy giờ?", option_a: "7 giờ tối", option_b: "12 giờ trưa", option_c: "7 giờ sáng", option_d: "2 giờ chiều", correct_answer: "c" },
  { question_text: "1 giờ = ? phút", option_a: "30", option_b: "100", option_c: "24", option_d: "60", correct_answer: "d" },
  { question_text: "Nửa giờ = ? phút", option_a: "30", option_b: "15", option_c: "45", option_d: "60", correct_answer: "a" },
  { question_text: "1 ngày = ? giờ", option_a: "12", option_b: "24", option_c: "48", option_d: "60", correct_answer: "b" },
  { question_text: "1 tuần = ? ngày", option_a: "5", option_b: "6", option_c: "7", option_d: "10", correct_answer: "c" },

  // === TIỀN VIỆT NAM ===
  { question_text: "Mua 1 cây bút 3000đ, đưa 5000đ. Được trả lại bao nhiêu?", option_a: "1000đ", option_b: "3000đ", option_c: "8000đ", option_d: "2000đ", correct_answer: "d" },
  { question_text: "2 quyển vở, mỗi quyển 4000đ. Hết bao nhiêu tiền?", option_a: "8000đ", option_b: "6000đ", option_c: "4000đ", option_d: "10000đ", correct_answer: "a" },
  { question_text: "Có 10000đ, mua kẹo 3000đ. Còn lại bao nhiêu?", option_a: "6000đ", option_b: "7000đ", option_c: "8000đ", option_d: "5000đ", correct_answer: "b" },
  { question_text: "3 cái bánh, mỗi cái 2000đ. Hết bao nhiêu?", option_a: "4000đ", option_b: "5000đ", option_c: "6000đ", option_d: "8000đ", correct_answer: "c" },
  { question_text: "Mua sách 15000đ, đưa 20000đ. Trả lại bao nhiêu?", option_a: "3000đ", option_b: "10000đ", option_c: "15000đ", option_d: "5000đ", correct_answer: "d" },

  // === BÀI TOÁN CÓ LỜI VĂN ĐƠN GIẢN ===
  { question_text: "Lan có 25 viên bi, Lan cho bạn 8 viên. Lan còn mấy viên bi?", option_a: "17", option_b: "16", option_c: "18", option_d: "15", correct_answer: "a" },
  { question_text: "Lớp 2A có 32 học sinh, lớp 2B có 28 học sinh. Hai lớp có tất cả bao nhiêu học sinh?", option_a: "58", option_b: "60", option_c: "62", option_d: "56", correct_answer: "b" },
  { question_text: "Mẹ mua 3 túi cam, mỗi túi 5 quả. Mẹ mua tất cả mấy quả cam?", option_a: "12", option_b: "8", option_c: "15", option_d: "18", correct_answer: "c" },
  { question_text: "Có 20 cái bánh chia đều cho 4 bạn. Mỗi bạn được mấy cái?", option_a: "4", option_b: "6", option_c: "8", option_d: "5", correct_answer: "d" },
  { question_text: "An có 45 trang sách, đã đọc 18 trang. An còn phải đọc mấy trang?", option_a: "27", option_b: "26", option_c: "28", option_d: "25", correct_answer: "a" },
];
