// Tiếng Việt trung bình - Sắp xếp câu, từ trái nghĩa/đồng nghĩa, điền từ
export const vietQuestionsMedium = [
  // === TỪ TRÁI NGHĨA ===
  { question_text: "Trái nghĩa của 'to' là gì?", option_a: "nhỏ", option_b: "lớn", option_c: "cao", option_d: "dài", correct_answer: "a" },
  { question_text: "Trái nghĩa của 'nóng' là gì?", option_a: "ấm", option_b: "lạnh", option_c: "mát", option_d: "nực", correct_answer: "b" },
  { question_text: "Trái nghĩa của 'dài' là gì?", option_a: "to", option_b: "nhỏ", option_c: "ngắn", option_d: "rộng", correct_answer: "c" },
  { question_text: "Trái nghĩa của 'đẹp' là gì?", option_a: "xinh", option_b: "tốt", option_c: "hay", option_d: "xấu", correct_answer: "d" },
  { question_text: "Trái nghĩa của 'sáng' là gì?", option_a: "tối", option_b: "đêm", option_c: "mờ", option_d: "đen", correct_answer: "a" },
  { question_text: "Trái nghĩa của 'vui' là gì?", option_a: "khóc", option_b: "buồn", option_c: "giận", option_d: "sợ", correct_answer: "b" },
  { question_text: "Trái nghĩa của 'nhanh' là gì?", option_a: "mau", option_b: "lẹ", option_c: "chậm", option_d: "gấp", correct_answer: "c" },
  { question_text: "Trái nghĩa của 'cao' là gì?", option_a: "to", option_b: "lớn", option_c: "dài", option_d: "thấp", correct_answer: "d" },
  { question_text: "Trái nghĩa của 'khỏe' là gì?", option_a: "yếu", option_b: "mạnh", option_c: "béo", option_d: "gầy", correct_answer: "a" },
  { question_text: "Trái nghĩa của 'giàu' là gì?", option_a: "ít", option_b: "nghèo", option_c: "thiếu", option_d: "hết", correct_answer: "b" },
  { question_text: "Trái nghĩa của 'đúng' là gì?", option_a: "phải", option_b: "hay", option_c: "sai", option_d: "dở", correct_answer: "c" },
  { question_text: "Trái nghĩa của 'trước' là gì?", option_a: "trên", option_b: "dưới", option_c: "bên", option_d: "sau", correct_answer: "d" },
  { question_text: "Trái nghĩa của 'già' là gì?", option_a: "trẻ", option_b: "nhỏ", option_c: "bé", option_d: "non", correct_answer: "a" },
  { question_text: "Trái nghĩa của 'mở' là gì?", option_a: "khép", option_b: "đóng", option_c: "gập", option_d: "che", correct_answer: "b" },
  { question_text: "Trái nghĩa của 'ngày' là gì?", option_a: "sáng", option_b: "chiều", option_c: "đêm", option_d: "tối", correct_answer: "c" },
  // === TỪ ĐỒNG NGHĨA ===
  { question_text: "Từ nào đồng nghĩa với 'xinh'?", option_a: "xấu", option_b: "to", option_c: "nhỏ", option_d: "đẹp", correct_answer: "d" },
  { question_text: "Từ nào đồng nghĩa với 'vui'?", option_a: "vui vẻ", option_b: "buồn", option_c: "giận", option_d: "sợ", correct_answer: "a" },
  { question_text: "Từ nào đồng nghĩa với 'nhanh'?", option_a: "chậm", option_b: "mau", option_c: "lâu", option_d: "muộn", correct_answer: "b" },
  { question_text: "Từ nào đồng nghĩa với 'chăm chỉ'?", option_a: "lười", option_b: "mệt", option_c: "siêng năng", option_d: "buồn ngủ", correct_answer: "c" },
  { question_text: "Từ nào đồng nghĩa với 'to'?", option_a: "nhỏ", option_b: "bé", option_c: "ngắn", option_d: "lớn", correct_answer: "d" },
  { question_text: "Từ nào đồng nghĩa với 'thông minh'?", option_a: "giỏi", option_b: "dốt", option_c: "lười", option_d: "chậm", correct_answer: "a" },
  { question_text: "Từ nào đồng nghĩa với 'dũng cảm'?", option_a: "sợ hãi", option_b: "can đảm", option_c: "nhút nhát", option_d: "yếu đuối", correct_answer: "b" },
  { question_text: "Từ nào đồng nghĩa với 'tốt bụng'?", option_a: "ác", option_b: "xấu", option_c: "hiền lành", option_d: "dữ", correct_answer: "c" },
  { question_text: "Từ nào đồng nghĩa với 'buồn'?", option_a: "vui", option_b: "hạnh phúc", option_c: "sung sướng", option_d: "u sầu", correct_answer: "d" },
  { question_text: "Từ nào đồng nghĩa với 'nhà'?", option_a: "gia đình", option_b: "trường", option_c: "chợ", option_d: "công viên", correct_answer: "a" },

  // === ĐIỀN TỪ VÀO CHỖ TRỐNG ===
  { question_text: "Em ... đến trường mỗi sáng.", option_a: "chạy", option_b: "đi", option_c: "bay", option_d: "bơi", correct_answer: "b" },
  { question_text: "Mặt trời ... ở phía đông.", option_a: "lặn", option_b: "tắt", option_c: "mọc", option_d: "chìm", correct_answer: "c" },
  { question_text: "Con mèo ... chuột.", option_a: "yêu", option_b: "thương", option_c: "giúp", option_d: "bắt", correct_answer: "d" },
  { question_text: "Bầu trời hôm nay rất ...", option_a: "xanh", option_b: "đỏ", option_c: "đen", option_d: "tím", correct_answer: "a" },
  { question_text: "Mùa đông trời rất ...", option_a: "nóng", option_b: "lạnh", option_c: "mát", option_d: "ấm", correct_answer: "b" },
  { question_text: "Con chim ... trên cành cây.", option_a: "bơi", option_b: "chạy", option_c: "hót", option_d: "nhảy", correct_answer: "c" },
  { question_text: "Hoa hồng có màu ...", option_a: "xanh", option_b: "vàng", option_c: "tím", option_d: "đỏ", correct_answer: "d" },
  { question_text: "Em ... bài trước khi đi ngủ.", option_a: "học", option_b: "chơi", option_c: "ăn", option_d: "xem", correct_answer: "a" },
  { question_text: "Cá ... dưới nước.", option_a: "bay", option_b: "bơi", option_c: "chạy", option_d: "nhảy", correct_answer: "b" },
  { question_text: "Mẹ ... cơm cho cả nhà.", option_a: "đọc", option_b: "viết", option_c: "nấu", option_d: "vẽ", correct_answer: "c" },
  // === SẮP XẾP TỪ THÀNH CÂU ===
  { question_text: "Sắp xếp: 'đi / Em / học / trường / đến'", option_a: "Em đi học đến trường", option_b: "Em đi đến trường học", option_c: "Đi học em đến trường", option_d: "Trường học em đi đến", correct_answer: "b" },
  { question_text: "Sắp xếp: 'hoa / Bông / đẹp / rất'", option_a: "Bông hoa rất đẹp", option_b: "Rất đẹp bông hoa", option_c: "Hoa bông rất đẹp", option_d: "Đẹp rất bông hoa", correct_answer: "a" },
  { question_text: "Sắp xếp: 'yêu / Mẹ / em / rất'", option_a: "Em rất yêu mẹ", option_b: "Mẹ rất yêu em", option_c: "Yêu mẹ em rất", option_d: "Rất yêu em mẹ", correct_answer: "b" },
  { question_text: "Sắp xếp: 'chơi / Các bạn / sân / ở / đang'", option_a: "Ở sân các bạn đang chơi", option_b: "Đang chơi các bạn ở sân", option_c: "Các bạn đang chơi ở sân", option_d: "Sân ở các bạn đang chơi", correct_answer: "c" },
  { question_text: "Sắp xếp: 'nắng / Hôm nay / trời / rất'", option_a: "Trời rất nắng hôm nay", option_b: "Nắng rất trời hôm nay", option_c: "Rất nắng hôm nay trời", option_d: "Hôm nay trời rất nắng", correct_answer: "d" },
  { question_text: "Sắp xếp: 'ăn / Con mèo / cá / thích'", option_a: "Con mèo thích ăn cá", option_b: "Ăn cá con mèo thích", option_c: "Thích ăn cá con mèo", option_d: "Cá thích ăn con mèo", correct_answer: "a" },
  { question_text: "Sắp xếp: 'đọc / Bố / báo / đang'", option_a: "Đang đọc bố báo", option_b: "Bố đang đọc báo", option_c: "Báo đang đọc bố", option_d: "Đọc báo bố đang", correct_answer: "b" },
  { question_text: "Sắp xếp: 'vẽ / Em / tranh / một / bức'", option_a: "Tranh em vẽ một bức", option_b: "Một bức tranh em vẽ", option_c: "Em vẽ một bức tranh", option_d: "Vẽ em một bức tranh", correct_answer: "c" },
  { question_text: "Sắp xếp: 'sáng / mọc / Mặt trời / buổi'", option_a: "Buổi sáng mọc mặt trời", option_b: "Mọc buổi sáng mặt trời", option_c: "Sáng buổi mặt trời mọc", option_d: "Mặt trời mọc buổi sáng", correct_answer: "d" },
  { question_text: "Sắp xếp: 'chăm / Bạn Lan / học / rất'", option_a: "Bạn Lan rất chăm học", option_b: "Rất chăm học bạn Lan", option_c: "Chăm học bạn Lan rất", option_d: "Học rất chăm bạn Lan", correct_answer: "a" },

  // === LOẠI TỪ ===
  { question_text: "Từ nào chỉ người?", option_a: "cây", option_b: "bác sĩ", option_c: "bàn", option_d: "sách", correct_answer: "b" },
  { question_text: "Từ nào chỉ con vật?", option_a: "bút", option_b: "nhà", option_c: "con thỏ", option_d: "hoa", correct_answer: "c" },
  { question_text: "Từ nào chỉ đồ vật?", option_a: "mèo", option_b: "cô giáo", option_c: "cây", option_d: "cái bàn", correct_answer: "d" },
  { question_text: "Từ nào chỉ hoạt động?", option_a: "chạy", option_b: "đẹp", option_c: "to", option_d: "xanh", correct_answer: "a" },
  { question_text: "Từ nào chỉ tính chất?", option_a: "đi", option_b: "xinh đẹp", option_c: "ăn", option_d: "viết", correct_answer: "b" },
  { question_text: "Từ nào chỉ cây cối?", option_a: "con gà", option_b: "cái ghế", option_c: "cây bàng", option_d: "bạn Hoa", correct_answer: "c" },
  { question_text: "Từ nào KHÔNG phải con vật?", option_a: "con chó", option_b: "con mèo", option_c: "con cá", option_d: "con đường", correct_answer: "d" },
  { question_text: "Từ nào chỉ màu sắc?", option_a: "tím", option_b: "chạy", option_c: "to", option_d: "nhà", correct_answer: "a" },
  { question_text: "Nhóm từ nào cùng loại?", option_a: "đỏ, xanh, vàng", option_b: "đỏ, chạy, nhà", option_c: "xanh, ăn, to", option_d: "vàng, bàn, đi", correct_answer: "a" },
  { question_text: "Nhóm từ nào cùng chỉ con vật?", option_a: "gà, vịt, bàn", option_b: "mèo, chó, thỏ", option_c: "cá, hoa, chim", option_d: "bò, cây, gà", correct_answer: "b" },

  // === CÂU HỎI VỀ BÀI THƠ/CÂU CA DAO ===
  { question_text: "'Công cha như núi Thái Sơn, Nghĩa mẹ như nước trong nguồn chảy ra'. Câu ca dao nói về ai?", option_a: "Thầy cô", option_b: "Bạn bè", option_c: "Cha mẹ", option_d: "Ông bà", correct_answer: "c" },
  { question_text: "'Đi một ngày đàng, học một sàng khôn'. Câu tục ngữ khuyên ta điều gì?", option_a: "Đi chơi nhiều", option_b: "Ở nhà", option_c: "Ngủ nhiều", option_d: "Đi để học hỏi", correct_answer: "d" },
  { question_text: "'Có công mài sắt, có ngày nên kim'. Câu tục ngữ khuyên ta điều gì?", option_a: "Kiên trì", option_b: "Lười biếng", option_c: "Nhanh nhẹn", option_d: "Thông minh", correct_answer: "a" },
  { question_text: "'Lá lành đùm lá rách'. Câu tục ngữ nói về điều gì?", option_a: "Ăn uống", option_b: "Giúp đỡ nhau", option_c: "Học giỏi", option_d: "Chơi vui", correct_answer: "b" },
  { question_text: "'Ăn quả nhớ kẻ trồng cây'. Câu tục ngữ dạy ta điều gì?", option_a: "Trồng cây", option_b: "Ăn nhiều", option_c: "Biết ơn", option_d: "Chăm chỉ", correct_answer: "c" },
];
